"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { cn } from "@/lib/utils";

/**
 * Will-I-Fail Self-Assessment
 *
 * 12 signal questions. Each question contributes weighted risk to one or two
 * NIST 800-171 families (AC, AT, AU, CM, IA, IR, MA, MP, PS, PE, RA, CA, SC, SI).
 *
 * Answer values:
 *  "yes"     → 0 risk      (in good shape)
 *  "partial" → half weight (drift / gaps)
 *  "no"      → full weight (likely to fail on assessment)
 *
 * The result panel sums risk per family, normalizes, and surfaces the three
 * families most likely to fail the engagement.
 */

type Answer = "yes" | "partial" | "no" | null;
type FamilyCode =
  | "AC" | "AT" | "AU" | "CM" | "IA" | "IR" | "MA"
  | "MP" | "PS" | "PE" | "RA" | "CA" | "SC" | "SI";

const FAMILY_NAMES: Record<FamilyCode, string> = {
  AC: "Access Control",
  AT: "Awareness & Training",
  AU: "Audit & Accountability",
  CM: "Configuration Management",
  IA: "Identification & Authentication",
  IR: "Incident Response",
  MA: "Maintenance",
  MP: "Media Protection",
  PS: "Personnel Security",
  PE: "Physical Protection",
  RA: "Risk Assessment",
  CA: "Security Assessment",
  SC: "System & Communications",
  SI: "System & Information Integrity"
};

type Question = {
  id: string;
  prompt: string;
  detail: string;
  weights: Partial<Record<FamilyCode, number>>; // per-family contribution if "no"
};

const QUESTIONS: Question[] = [
  {
    id: "mfa",
    prompt: "Privileged accounts use phishing-resistant MFA (FIDO2 or hardware tokens).",
    detail: "Software OTP is no longer sufficient for the privileged tier.",
    weights: { IA: 3, AC: 1 }
  },
  {
    id: "logs",
    prompt: "Audit logs from CUI systems are retained 12+ months online.",
    detail: "Retention shorter than one year fails the AU family on first pass.",
    weights: { AU: 3 }
  },
  {
    id: "boundary",
    prompt: "An authorization boundary diagram exists, signed within the last 12 months.",
    detail: "An unsigned, stale, or absent boundary diagram halts the assessment.",
    weights: { CA: 2, SC: 1 }
  },
  {
    id: "ir-tabletop",
    prompt: "Our incident response plan has been tabletop-exercised in the last 12 months.",
    detail: "A plan without exercise records is treated as not implemented.",
    weights: { IR: 3 }
  },
  {
    id: "ssp",
    prompt: "Our SSP is hand-authored — not auto-generated by a readiness tool.",
    detail: "Tool-exported SSPs routinely fail because they cannot answer follow-up questions.",
    weights: { CA: 3 }
  },
  {
    id: "fips",
    prompt: "FIPS-validated cryptography protects CUI at rest and in transit, by data class.",
    detail: "Bring-your-own-encryption and non-validated modules do not qualify.",
    weights: { SC: 3 }
  },
  {
    id: "vuln",
    prompt: "Vulnerability scans are run monthly with a documented closure SLA.",
    detail: "Ad-hoc scanning and undocumented closure timelines fail SI and weaken RA.",
    weights: { SI: 2, RA: 1 }
  },
  {
    id: "cui-marking",
    prompt: "CUI marking is consistent on documents, emails, and removable media.",
    detail: "Inconsistent marking is the most common MP family failure.",
    weights: { MP: 2, AT: 1 }
  },
  {
    id: "ps-access",
    prompt: "Personnel security records cross-walk to system access provisioning.",
    detail: "HR clearance evidence not linked to access grants fails PS on sample test.",
    weights: { PS: 2 }
  },
  {
    id: "maintenance",
    prompt: "Internal and vendor maintenance access is logged, reviewed, and tied to a ticket.",
    detail: "Vendor access without ticket reference is the recurring MA family finding.",
    weights: { MA: 2 }
  },
  {
    id: "physical",
    prompt: "Visitor and after-hours physical access is logged and retained 90+ days.",
    detail: "Cleaning staff and visitor entries are routinely missed.",
    weights: { PE: 2 }
  },
  {
    id: "config",
    prompt: "Configuration baselines exist per system class and are version-controlled.",
    detail: "Baselines that live in a Word document fail the CM family.",
    weights: { CM: 2 }
  }
];

function risk(answer: Answer, weight: number): number {
  if (answer === "no") return weight;
  if (answer === "partial") return weight / 2;
  return 0;
}

function severity(score: number): "low" | "moderate" | "high" {
  if (score >= 2.5) return "high";
  if (score >= 1) return "moderate";
  return "low";
}

const SEVERITY_CLASS: Record<"low" | "moderate" | "high", string> = {
  low: "border-signal-green/50 text-signal-green",
  moderate: "border-signal-amber/50 text-signal-amber",
  high: "border-signal-red/50 text-signal-red"
};

export function WillIFail() {
  const [answers, setAnswers] = useState<Record<string, Answer>>(
    Object.fromEntries(QUESTIONS.map((q) => [q.id, null]))
  );

  const answeredCount = Object.values(answers).filter((v) => v !== null).length;
  const allAnswered = answeredCount === QUESTIONS.length;

  const familyRisk = useMemo(() => {
    const totals: Record<FamilyCode, number> = {} as Record<FamilyCode, number>;
    for (const fc of Object.keys(FAMILY_NAMES) as FamilyCode[]) {
      totals[fc] = 0;
    }
    for (const q of QUESTIONS) {
      const a = answers[q.id];
      if (!a) continue;
      for (const [family, weight] of Object.entries(q.weights) as [FamilyCode, number][]) {
        totals[family] = (totals[family] ?? 0) + risk(a, weight);
      }
    }
    return totals;
  }, [answers]);

  const ranked = useMemo(() => {
    return (Object.entries(familyRisk) as [FamilyCode, number][])
      .map(([code, score]) => ({ code, name: FAMILY_NAMES[code], score, severity: severity(score) }))
      .sort((a, b) => b.score - a.score);
  }, [familyRisk]);

  const top3 = ranked.slice(0, 3);
  const overallHigh = top3.filter((f) => f.severity === "high").length;

  return (
    <div className="grid gap-10 lg:grid-cols-[1.4fr_1fr]">
      {/* QUESTIONS */}
      <div>
        <div className="mb-6 flex items-baseline justify-between">
          <h2 className="font-serif text-2xl text-bone-50">12 questions</h2>
          <div className="font-mono text-[11px] tracking-widest2 text-bone-400">
            {answeredCount} / {QUESTIONS.length} ANSWERED
          </div>
        </div>

        <ol className="space-y-4">
          {QUESTIONS.map((q, i) => (
            <li
              key={q.id}
              className={cn(
                "border bg-ink-900 p-6 transition",
                answers[q.id] ? "border-gold-300/40" : "border-ink-700"
              )}
            >
              <div className="flex items-baseline justify-between gap-4">
                <span className="font-mono text-[11px] tracking-widest2 text-gold-300">
                  Q{String(i + 1).padStart(2, "0")}
                </span>
                <span className="font-mono text-[10px] tracking-widest2 text-bone-400">
                  {Object.keys(q.weights).join(" · ")}
                </span>
              </div>
              <h3 className="mt-3 font-serif text-xl text-bone-50">{q.prompt}</h3>
              <p className="mt-2 text-sm text-bone-300">{q.detail}</p>

              <div
                role="radiogroup"
                aria-label={q.prompt}
                className="mt-5 grid gap-2 sm:grid-cols-3"
              >
                {(["yes", "partial", "no"] as const).map((value) => {
                  const selected = answers[q.id] === value;
                  return (
                    <button
                      key={value}
                      type="button"
                      role="radio"
                      aria-checked={selected}
                      onClick={() => setAnswers((p) => ({ ...p, [q.id]: value }))}
                      className={cn(
                        "border px-3 py-2.5 text-sm transition text-left",
                        selected
                          ? value === "yes"
                            ? "border-signal-green/70 bg-signal-green/15 text-bone-50"
                            : value === "partial"
                            ? "border-signal-amber/70 bg-signal-amber/15 text-bone-50"
                            : "border-signal-red/70 bg-signal-red/15 text-bone-50"
                          : "border-ink-700 text-bone-300 hover:border-bone-300"
                      )}
                    >
                      <span className="font-mono text-[10px] tracking-widest2 text-bone-400">
                        {value === "yes" ? "YES" : value === "partial" ? "PARTIAL" : "NO"}
                      </span>
                      <span className="mt-1 block">
                        {value === "yes"
                          ? "True today"
                          : value === "partial"
                          ? "Partially true"
                          : "Not true"}
                      </span>
                    </button>
                  );
                })}
              </div>
            </li>
          ))}
        </ol>
      </div>

      {/* RESULTS */}
      <aside>
        <div className="sticky top-28 space-y-6">
          <div className="border border-gold-300/40 bg-ink-900 p-7 shadow-gilt">
            <div className="font-mono text-[10px] tracking-widest2 text-gold-300">
              FAMILIES MOST LIKELY TO FAIL
            </div>

            {!allAnswered && (
              <p className="mt-4 text-sm text-bone-300">
                Answer all 12 questions to see the three families most likely to drop your
                engagement. The ranking updates as you go.
              </p>
            )}

            {answeredCount > 0 && (
              <ol className="mt-5 space-y-3">
                {top3.map((f, i) => (
                  <motion.li
                    key={f.code}
                    initial={{ opacity: 0, y: 4 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3, delay: i * 0.05 }}
                    className={cn("border bg-ink-950 p-4", SEVERITY_CLASS[f.severity])}
                  >
                    <div className="flex items-baseline justify-between">
                      <div className="flex items-baseline gap-3">
                        <span className="font-mono text-[10px] tracking-widest2">
                          #{i + 1}
                        </span>
                        <span className="font-mono text-[11px] tracking-widest2">{f.code}</span>
                      </div>
                      <span className="font-mono text-[10px] tracking-widest2 uppercase">
                        {f.severity}
                      </span>
                    </div>
                    <div className="mt-2 font-serif text-lg text-bone-50">{f.name}</div>
                  </motion.li>
                ))}
              </ol>
            )}

            {allAnswered && (
              <div className="mt-5 border-t border-ink-700 pt-5 text-sm text-bone-200">
                {overallHigh === 0 && (
                  <p>
                    No family rates as high risk on the signal questions you answered. A formal Gap
                    Assessment confirms whether the artifact posture matches the operational claim.
                  </p>
                )}
                {overallHigh === 1 && (
                  <p>
                    One family rates as high risk. That is a typical and manageable engagement
                    profile &mdash; a focused remediation surge brings it back inside the threshold.
                  </p>
                )}
                {overallHigh === 2 && (
                  <p>
                    Two families rate as high risk. The engagement is salvageable but the path is
                    Remediation Surge before C3PAO scheduling, not after.
                  </p>
                )}
                {overallHigh >= 3 && (
                  <p>
                    Three or more families rate as high risk. This is the profile we most often see
                    in pre-engagement triage. Certification is achievable but the runway is{" "}
                    <strong>120+ days</strong>, not 60. Start the Gap Assessment this quarter.
                  </p>
                )}
              </div>
            )}

            <Link
              href="/contact"
              className="mt-7 inline-flex w-full items-center justify-center gap-2 bg-gold-300 px-5 py-3 text-sm font-medium text-ink-950 hover:bg-gold-200"
            >
              Send results to a partner &rarr;
            </Link>
            <p className="mt-3 text-[11px] text-bone-400">
              We use the family risk profile to scope a 15-minute triage call. No marketing list.
            </p>
          </div>

          {/* Full ranking */}
          {answeredCount > 0 && (
            <div className="border border-ink-700 bg-ink-900 p-6">
              <div className="font-mono text-[10px] tracking-widest2 text-bone-400">
                ALL 14 FAMILIES, RANKED
              </div>
              <ul className="mt-4 space-y-2 text-sm">
                {ranked.map((f) => (
                  <li
                    key={f.code}
                    className="flex items-baseline justify-between gap-3 border-b border-ink-700 pb-2 last:border-0 last:pb-0"
                  >
                    <div className="flex items-baseline gap-3">
                      <span className="font-mono text-[10px] tracking-widest2 text-bone-400 w-6">
                        {f.code}
                      </span>
                      <span className="text-bone-200">{f.name}</span>
                    </div>
                    <span
                      className={cn(
                        "font-mono text-[10px] tracking-widest2 uppercase",
                        f.severity === "high"
                          ? "text-signal-red"
                          : f.severity === "moderate"
                          ? "text-signal-amber"
                          : "text-signal-green"
                      )}
                    >
                      {f.severity}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </aside>
    </div>
  );
}
